import Foundation
import SwiftData
import Combine

/// Service for managing app settings with SwiftData persistence
@MainActor
final class SettingsService: ObservableObject {
    static let shared = SettingsService()

    @Published private(set) var settings: AppSettings

    private var modelContext: ModelContext?

    private init() {
        // Start with default settings
        self.settings = AppSettings()

        // Setup persistence
        setupPersistence()
    }

    // MARK: - Persistence

    private func setupPersistence() {
        do {
            let schema = Schema([ClipItem.self, Collection.self, AppSettings.self])
            let modelConfiguration = ModelConfiguration(schema: schema, isStoredInMemoryOnly: false)
            let container = try ModelContainer(for: schema, configurations: [modelConfiguration])
            modelContext = ModelContext(container)
            loadSettings()
        } catch {
            print("Failed to setup SwiftData for settings: \(error)")
        }
    }

    private func loadSettings() {
        guard let context = modelContext else { return }

        let descriptor = FetchDescriptor<AppSettings>()

        do {
            let existingSettings = try context.fetch(descriptor)
            if let existing = existingSettings.first {
                settings = existing
            } else {
                // Create default settings
                let newSettings = AppSettings()
                context.insert(newSettings)
                try context.save()
                settings = newSettings
            }
        } catch {
            print("Failed to load settings: \(error)")
        }
    }

    func save() {
        guard let context = modelContext else { return }
        do {
            try context.save()
            objectWillChange.send()
        } catch {
            print("Failed to save settings: \(error)")
        }
    }

    // MARK: - Settings Accessors

    var historyLimit: Int {
        get { settings.historyLimit }
        set {
            settings.historyLimit = newValue
            save()
            // Notify ClipboardMonitor of the change
            ClipboardMonitor.shared.setHistoryLimit(newValue)
        }
    }

    var launchAtLogin: Bool {
        get { settings.launchAtLogin }
        set {
            settings.launchAtLogin = newValue
            save()
            // TODO: Actually enable/disable launch at login via SMAppService
        }
    }

    var compactMode: Bool {
        get { settings.compactMode }
        set {
            settings.compactMode = newValue
            save()
        }
    }

    var soundEnabled: Bool {
        get { settings.soundEnabled }
        set {
            settings.soundEnabled = newValue
            save()
        }
    }

    var pasteAsPlainTextByDefault: Bool {
        get { settings.pasteAsPlainTextByDefault }
        set {
            settings.pasteAsPlainTextByDefault = newValue
            save()
        }
    }

    var ignoreAutoGenerated: Bool {
        get { settings.ignoreAutoGenerated }
        set {
            settings.ignoreAutoGenerated = newValue
            save()
        }
    }

    var ignorePasswordManagers: Bool {
        get { settings.ignorePasswordManagers ?? true }  // Default to true if nil (migration case)
        set {
            settings.ignorePasswordManagers = newValue
            save()
            // Update ClipboardMonitor's password manager filtering
            ClipboardMonitor.shared.setIgnorePasswordManagers(newValue)
        }
    }

    var closeOnFocusLoss: Bool {
        get { settings.closeOnFocusLoss ?? false }  // Default to false
        set {
            settings.closeOnFocusLoss = newValue
            save()
        }
    }

    var showCloseButton: Bool {
        get { settings.showCloseButton ?? true }  // Default to true
        set {
            settings.showCloseButton = newValue
            save()
        }
    }

    var autoDeleteAfterDays: Int {
        get { settings.autoDeleteAfterDays ?? 0 }  // 0 means disabled
        set {
            settings.autoDeleteAfterDays = newValue
            save()
            // Trigger cleanup if enabled
            if newValue > 0 {
                ClipboardMonitor.shared.performAutoCleanup(olderThanDays: newValue)
            }
        }
    }

    var ignoredAppBundleIDs: [String] {
        get { settings.ignoredAppBundleIDs }
        set {
            settings.ignoredAppBundleIDs = newValue
            save()
            // Update ClipboardMonitor
            for bundleID in newValue {
                ClipboardMonitor.shared.addIgnoredApp(bundleID)
            }
        }
    }

    func addIgnoredApp(_ bundleID: String) {
        if !settings.ignoredAppBundleIDs.contains(bundleID) {
            settings.ignoredAppBundleIDs.append(bundleID)
            save()
            ClipboardMonitor.shared.addIgnoredApp(bundleID)
        }
    }

    func removeIgnoredApp(_ bundleID: String) {
        settings.ignoredAppBundleIDs.removeAll { $0 == bundleID }
        save()
        ClipboardMonitor.shared.removeIgnoredApp(bundleID)
    }
}
