import Foundation
import SwiftData

/// Pause duration options for clipboard capture
enum PauseDuration: String, Codable, CaseIterable {
    case fiveMinutes = "5min"
    case fifteenMinutes = "15min"
    case oneHour = "1hour"
    case untilResume = "manual"

    var displayName: String {
        switch self {
        case .fiveMinutes: return "5 minutes"
        case .fifteenMinutes: return "15 minutes"
        case .oneHour: return "1 hour"
        case .untilResume: return "Until resumed"
        }
    }

    var interval: TimeInterval? {
        switch self {
        case .fiveMinutes: return 5 * 60
        case .fifteenMinutes: return 15 * 60
        case .oneHour: return 60 * 60
        case .untilResume: return nil
        }
    }
}

@Model
final class AppSettings {
    @Attribute(.unique) var id: UUID

    // Display
    var showInMenuBar: Bool
    var showInDock: Bool
    var compactMode: Bool

    // Startup
    var launchAtLogin: Bool

    // Clipboard
    var historyLimit: Int
    var ignoredAppBundleIDs: [String]
    var ignoreAutoGenerated: Bool
    // Use optional with default to allow schema migration
    var ignorePasswordManagers: Bool?

    // Hotkeys (stored as serialized strings)
    var mainHotkey: String
    var pasteStackHotkey: String

    // Paste behavior
    var pasteAsPlainTextByDefault: Bool

    // Sound
    var soundEnabled: Bool

    // Panel behavior
    var closeOnFocusLoss: Bool?
    var showCloseButton: Bool?

    // Auto-cleanup
    var autoDeleteAfterDays: Int?  // nil or 0 means disabled

    // Pause state
    var isPaused: Bool
    var pauseUntil: Date?

    init() {
        self.id = UUID()
        self.showInMenuBar = true
        self.showInDock = false
        self.compactMode = false
        self.launchAtLogin = false
        self.historyLimit = 1000
        self.ignoredAppBundleIDs = []
        self.ignoreAutoGenerated = false
        self.ignorePasswordManagers = true  // Default for new installs
        self.mainHotkey = "shift+cmd+v"
        self.pasteStackHotkey = "shift+cmd+c"
        self.pasteAsPlainTextByDefault = false
        self.soundEnabled = false
        self.closeOnFocusLoss = false
        self.showCloseButton = true
        self.autoDeleteAfterDays = 0  // Disabled by default
        self.isPaused = false
        self.pauseUntil = nil
    }

    // MARK: - Pause Management

    func pause(for duration: PauseDuration) {
        isPaused = true
        if let interval = duration.interval {
            pauseUntil = Date().addingTimeInterval(interval)
        } else {
            pauseUntil = nil
        }
    }

    func resumeCapture() {
        isPaused = false
        pauseUntil = nil
    }

    func checkAndResumeIfNeeded() {
        guard isPaused, let until = pauseUntil else { return }
        if Date() > until {
            resumeCapture()
        }
    }

    var pauseTimeRemaining: TimeInterval? {
        guard isPaused, let until = pauseUntil else { return nil }
        let remaining = until.timeIntervalSince(Date())
        return remaining > 0 ? remaining : nil
    }
}
